tinaQuotes = [
"Come on iiiin, you are missing the Fuun!",
"All around the Sta-actus plant, the stalker chased the bandit, the stalker thought 'twas all in fun - POP! Goes the bandit!",
"Oh haiiii!",
"Roland told me you were comin' - I still owe him for all that buttcrap with General Rancid. So, you gotta hijack a train, hunh? Chiiild's play! Lemme introduce you to my ladies.",
"Runnin', runnin', runnin', I'm runnin' over here, run, run, run-run, run.",
"This here's Mushy Snugglebites, and this is Felicia Sexopants. These fiiiine-ass womens could stop that train for yas, but I'ma need their badonkadonks first, and they got stoled by the bandits a few days ago. Go get 'em!",
"Naptime!",
"That's right, bitches - my big brudder's about to teach you some MANNERS. Nobody steals Mushy Snugglebites' badonkadonk and lives!",
"That's Mushy Snugglebites' badonkadonk. She's my main squeeze. Lady's got a gut fulla' dynamite and a booty like POOOW!",
"Got the badonkadonks? Best day evaaaa. Bring 'em back here and I'll use 'em to make some fine-ass damsels who can hijack that train for yas.",
"Hey I told ya'z to get outta heeya, get out or do I gotta shank a bitch?",
"Get-outta-my-shop-or-I'll-punch-yo-butt. That's-how-Tiny-Tina-roll.",
"(Singing) Put a little bomb in the hot ass damsel, blow stuff up and make people die.",
"I'm a little teapot, bloody and cut. Here is my handle and here is my butt.*explosion noise* Oops.",
"Squishy. Squishy squishy squishy.",
"Oh daaaaaayum, you lookin' good, ladies. Let's get to work.",
"That's right. Twin sisters, man. Hhhahhhhhh. Take 'em. Take 'em take 'em take 'em take 'em.",
"Just put my damsels near the choo-choo track and set 'em off! Good plan? Great plan!",
"You're cordially invited BITCH!!!",
"When you are ready to begin the Tea-Party, please smack Mister Flesh Stick in his bitch face.",
"Gonna eat so many goddamn crumpets, it's going to be a Crumpocalypse.",
"Ten... Nine... *launches rockets* I got bored.",
"BURN ALL THE BABIES!!!!!",
"(Cute yawning noise)",
"Make it RAAAAAAAAAAAAAIN!",
"Sup, sucka? It's Tina. I wrote you a poem and it goes a little somethin' like this BREAK IT DOWN. Ahem. Kill Jack. Kill Jack. Kill Jack kill Jack kill Jack KIIIILL JAAAAACK! Kill Jack. A poem by Tiny Tina.",
"Climb the pipe to the train or you'll go insane wut wut. That's a rap song I wrote.",
"Get some cookies, so you can eat 'em and grow up big and strong and kick Piston in the butt-butt.",
"Real badasses eat chocolate chip cookies, I'ma gonna get that tattooed across my back in Old English font.",
"Wait a minute. Those cookies weren't chocolate chip. Those...are...raisins. WHYYYYYY-HY-HYYYYY?! SHAWTY, DESTROY ALL THE FOOD DISPENSERS! WIPE THE RAISIN ABOMINATIONS OFF THE MAP! I JUST WANTED CHOCOLATE CHIP COOKIES! WHY DO BAD THINGS HAPPEN TO GOOD PEOPLE?",
"Ohmygodohmygodohmygod. Do you know who just arrived in Beatdown? SULLY THE STABBER! He's my THIRD favorite mass-murderer in the ENTIRE WORLD! You HAVE to go get his autograph for me.",
"Get his signature on this. Please. PLEASEpleasepleasepleasepleaseplease! If you don't get his autograph I'm gonna DIEEEEE. He's my favoritest. He killed every living person on the Bathymas with nothing but a rusty butterknife. If you don't take it I'm gonna start crying. Please. Please. Please. Please. Please. [making a song out of it] oh-baby please please PLEASE! That was 'Please' by Tiny Tina with Vault Hunter on bass.",
"He said...no? Well. There's only one thing to do -- look him in the eye, nod politely, and KILL THE LIVING CRAP OUT OF HIM!",
"You come up in my face, and you DON'T GOT BOMB PARTS, you KNOW I'm throwing hands.",
"Oh, hello! I didn't see you there. I was just on an important mission to save my friends and AREN'T YOU SUPPOSED TO BE DOING THE SAME THING?!",
"Gonna go blat-blat-blat on the vine-freaks. \n Rat-tat-tat till their brain leaks. \n Chill, girl, just droppin' some bars. Go do the thing.",
"I wanna shoot the cannon again! AGAIN! But Lil said no. BLEEPING CURSE WORDS!",
"You kiddos killed that butt-bot so, so good! (cackle) Butt-bot.",
"Come on, Mordy. You got this! You gonna be all right.",
"MORDY'S ALL BETTER AND ELLIE FIXED THE CAMP'S COFFEE MACHINE AND I CAN'T STOP YELLING ABOUT EITHER ONE OF THOSE THINGS!",
"Yo yo yo. You kill that vineyman up on vineyville yet?",
"I left some reeaaal sexy bombs back on Sanctuary. Oh, just thinkin' bout 'em... come on, think about 'em with me. Yeeeeeah. Together now. Hohhhhh.",
"That. Was. The BIGGESTEST BOOM OF ALL TIME! Gotta give it to Lilly-of-the-valley, she knows how to kill a baddo in style.",
"Seriously, though. Vaulty-Vault, you was there for me in the dark times. That's fo' life.",
"So, just saying, it's probably my birthday, and you ain't got me nothing. Mini-moonshot cannon. Just wanna put that in your head.",
]